---
title: "Class6 R functions"
author: "Hongji Jiang"
date: "10/17/2019"
output: github_document
  #html_document: default
  #pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#This is my work from class6 **BIMM143**.

```{r}

#this is to demo a code chunk
plot(1:10)
```

##Practice Reading Files(again...)
```{r}
read.table("test1.txt",sep = ",", header = TRUE)
read.table("test2.txt",sep = "$", header = TRUE)
read.table("test3.txt")
```
```{r}
add <- function(x, y=1) {
# Sum the input x and y 
  x+y
}
```
```{r}
add(1)

add(5,5)

```
```{r}
rescale <- function(x) {
   rng <-range(x)
   (x - rng[1]) / (rng[2] - rng[1])
}

```
```{r}
rescale(1:10)
```
Test some
```{r}
x<-c(1,2,NA,3,10)
rescale(c(1,2,NA,3,10))
rng = range(x,na.rm = TRUE)
rng
```
```{r}
rescale2 <- function(x) {
   rng <-range(x,na.rm = TRUE)
   (x - rng[1]) / (rng[2] - rng[1])
}
```
```{r}
rescale2(x)
```
```{r}
 rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
    rng <-range(x, na.rm=na.rm)
    print("Hello")
   answer <- (x - rng[1]) / (rng[2] - rng[1])
   print("is it me you are looking for?")
   if(plot) {
      plot(answer, typ="b", lwd=4)
   }
   print("I can see it in ...")
   return(answer)
}
```
```{r}
rescale3(1:10,plot=TRUE)
```

#section2

Install the **bio3d** pakage for sequence and structure analysis
```{r}
library(bio3d)
s1 <- read.pdb("4AKE")  # kinase with drug
s2 <- read.pdb("1AKE")  # kinase no drug
s3 <- read.pdb("1E4Y")  # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```
```{r}
hc <- hclust( dist( rbind(s1.b, s2.b, s3.b) ) )
plot(hc)
```
```{r}
# function describtion 
# this function takes in one argument x that is the name 
# of the pdb file 
# Output: it plots a plot with residue on x-label and 
# Bfactor on the y-label
plotp <- function(x)
{
  # read.pdb reads a protein data bank coordinate file
  # argument x is the name of the PDB file to read 
  s = read.pdb(x)
  # trim.pdb produces a smaller pdb object
  # it contains a subset of atoms 
  # argument elety: a character vector of atom names.
  # argument chain a character vecter of chain identifiers
  s.chainA <- trim.pdb(s, chain="A", elety="CA")
  s.b <- s.chainA$atom$b
  # plotb3: Draw a standard scatter plot
  # with optional secondary structure in the marginal regions.
  plotb3(s.b, sse=s.chainA, typ="l", ylab="Bfactor")
}
# Here I use the three examples above 
# to test my function
plotp("4AKE")
plotp("1AKE")
plotp("1E4Y")
#J
```

